import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const clashDisplay = localFont({
  variable: '--font-clash-display',
  src: [
    {
      path: '../public/font/ClashDisplay-Extralight.otf',
      weight: '200',
    },
    {
      path: '../public/font/ClashDisplay-Light.otf',
      weight: '300',
    },
    {
      path: '../public/font/ClashDisplay-Regular.otf',
      weight: '400',
    },
    {
      path: '../public/font/ClashDisplay-Medium.otf',
      weight: '500',
    },
    {
      path: '../public/font/ClashDisplay-Semibold.otf',
      weight: '600',
    },
    {
      path: '../public/font/ClashDisplay-Bold.otf',
      weight: '700',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} ${geistMono.className} ${clashDisplay.variable} h-full antialiased`}>
      <body className='flex min-h-full flex-col'>{children}</body>
    </html>
  );
}
